dataset: S1_D80

pear_directory: /home/boydpeters/pear-0.9.11-linux-x86_64/bin/pear

prefix:
    cleaved:
        name: A
        sequence: CTTTTCCGTATATCTCGCCAG
    uncleaved:
        name: W
        sequence: GGGAAACAAACAAA

suffix:
    cleaved:
        name: X
        sequence: AAAAAGAAA
    uncleaved:
        name: X
        sequence: AAAAAGAAA

info_patterns:
    driver_round: "(?<=D)([0-9]+)"
    selection: "(S[0-9]+)"
    ligand_present: "(?<=L)([0-1]+)"