dataset: S1_D80

pear_directory: /home/boydpeters/pear-0.9.11-linux-x86_64/bin/pear

prefixes:
    cleaved:
        sequence: CTTTTCCGTATATCTCGCCAG
        name: A
    uncleaved:
        sequence: GGGAAACAAACAAA
        name: W
    other:
        sequence: ACAAAACAAAAC
        name: Z

suffix:
    cleaved:
        sequence: AAAAAGAAA
        name: X
    uncleaved:
        sequence: AAAAAGAAA
        name: X

info_patterns:
    driver_round: "(?<=D)([0-9]+)"
    selection: "(S[0-9]+)"
    ligand_present: "(?<=L)([0-1]+)"